### ISSUE TITLE
game menu with multiplayer and single player when you open the game and ability to open and use the "options" button

### ISSUE THREAD

**Issue by Mikey12006441** [michaljaz/webmc#113]
game menu with multiplayer and single player when you open the game and ability to open and use the "options" button

**Comment by michaljaz** [comment]
Oh yeah

**Comment by Mikey12006441** [comment]
yea
________________________________

**Comment by Mikey12006441** [comment]
did you forget to add that
________________________________

**Comment by crazycrixar** [comment]
> Oh yeah

+1 do it pls it would be great
