### ISSUE TITLE
stuff

### ISSUE THREAD

**Issue by Mikey12006441** [michaljaz/webmc#114]
add crafting and also add mobs add the ability to hit entities (like punching them and killing them) and fix the block placements like when you place them they are delayed and sometimes don't place. another issue is when you die and respawn  you cant break blocks you don't take damage. And also fix the servers frome kicking you off the server or not connecting

**Comment by Soup333** [comment]
Could you maybe make the title shorter it should be short and simple. Also you put multiple things into one issue.

**Comment by dragonismcode** [comment]
Organized their gibberish:
- add crafting and
- add mobs
- add the ability to hit entities (like punching them and killing them)
- fix the block placements (when you place them they are delayed and sometimes don't place) 
- when you die and respawn you cant break blocks or take damage. 
- fix the server(s) from kicking you off the server or not connecting

**Comment by Mikey12006441** [comment]
> Could you maybe make the title shorter it should be short and simple. Also you put multiple things into one issue.

ok will put in more organized format and fix title
