### ISSUE TITLE
Doc to connect to a specific server instance

### ISSUE THREAD

**Issue by nodje** [michaljaz/webmc#115]
Hi @michaljaz ,

I'd like to connect this client to a self-hosted Minecraft server.
From the URL of the demo instance (`server=95.111.249.143:10000&nick=RestSeal&proxy=production`, I gather:
- `server` is where I can indicate server IP and port
- `nick` self-explanatory
- `proxy` I'm not too sure here what's needed.

From the dev doc, I see that it's using webmcproxy.glitch.me.
But what is this? A WebSocket proxy afaiu ?

How do you configure this? Deploy one? Using your code? 
What are the requirement, can any WS proxy be used?

It'd be nice to put a few lines in the README to explain how to use it.

**Comment by michaljaz** [comment]
ok i will add it

**Comment by michaljaz** [comment]
added :)
