### ISSUE TITLE
add the ability to see your hand and go in F5 mode (change pov)

### ISSUE THREAD

**Issue by Mikey12006441** [michaljaz/webmc#116]

**Comment by michaljaz** [comment]
f5 will reload your browser tab, so it will not work :(

**Comment by Soup333** [comment]
> f5 will reload your browser tab, so it will not work :(

How about alt 5

**Comment by michaljaz** [comment]
good idea

**Comment by Mikey12006441** [comment]
> f5 will reload your browser tab, so it will not work :(

well what if you change you keyboard setting to make the top row keys function as regular keys and you on windows

**Comment by Soup333** [comment]
> good idea

Nvm, alt 5 goes to 5th tab and cntrl 5 does that in Firefox I think.

**Comment by DakshG07** [comment]
Shift+5?
