### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by TheOneWhoIsCool** [michaljaz/webmc#118]
I’ve been trying to play for 20 minutes now. It doesn’t connect to server, is it because I’m on iPad? Hi (same thing happening with https://classic.minecraft.net/(desktop turn on with apple keyboard))

**Comment by michaljaz** [comment]
Try changing nick

**Comment by michaljaz** [comment]
what text you have on loading screen?

**Comment by TheOneWhoIsCool** [comment]
Connecting to 95.111.249.143:10000...

**Comment by TheOneWhoIsCool** [comment]
> what text you have on loading screen?
Connecting to 95.111.249.143:10000...

**Comment by TheOneWhoIsCool** [comment]
![Uploading 107FAE79-1EBF-4C8D-BDFA-8B3E7021C07C.png…]()

**Comment by Zi7ar21** [comment]
> Try changing nick in url param

I had the same problem where it wouldn't let me connect and would say "invalid session" but this fixed it

**Comment by TheOneWhoIsCool** [comment]
@Zi7ar21 wow

**Comment by TheOneWhoIsCool** [comment]
‘@Zi7ar21’ wdym change nick

**Comment by TheOneWhoIsCool** [comment]
‘Zi7ar21, michaljaz. this is what it looks like’
![6C876093-253B-45B2-B140-D071445DCF0C](https://user-images.githubusercontent.com/95980743/145726255-71816a81-aa83-4cfa-8894-9e3a0e4d2d6a.png) 

> Connecting to 95.111.249.143:10000...

///////////// ![2F610E7E-57F9-421F-8C9B-999B98CC503F](https://user-images.githubusercontent.com/95980743/145726344-61b1274e-309f-4f35-bb2f-908210217697.gif)

**Comment by michaljaz** [comment]
open debug console with CTRL+SHIFT+I and send log here

**Comment by TheOneWhoIsCool** [comment]
I’m on iPad, of course I can’t do that, it works on my school chromebook. it said invalid session at first but I changed nick

**Comment by michaljaz** [comment]
Try changing nick again and it will work.

**Comment by TheOneWhoIsCool** [comment]
ok

**Comment by TheOneWhoIsCool** [comment]
sadly, it didn’t work :(
