### ISSUE TITLE
Waiting for Proxy

### ISSUE THREAD

**Issue by ldhandley** [michaljaz/webmc#122]
I'm getting "Waiting for Proxy" on https://minecraft.js.org.  Should this be working?

Update: If I wait long enough, I get a message telling me it's "connecting."  But it never does.

**Comment by Baggette** [comment]
> I'm getting "Waiting for Proxy" on https://minecraft.js.org. Should this be working?
> 
> Update: If I wait long enough, I get a message telling me it's "connecting." But it never does.

I have the exact same problem. most times it gets past waiting for proxy but it never actually connects to the server.

**Comment by pecocksir** [comment]
Same here,
![Screenshot 2022-01-21 11 05 48 AM](https://user-images.githubusercontent.com/95301666/150560124-ff4decc9-6b61-474f-80bf-3e5343d31e13.png)
Gets stuck on connecting

**Comment by michaljaz** [comment]
yeah, this is because default minecraft server is broken

**Comment by michaljaz** [comment]
i should add timeout

**Comment by cooldude-222** [comment]
Is there another server that works

**Comment by michaljaz** [comment]
1.16.5 offline mode should work

**Comment by DakshG07** [comment]
How do you access that?

**Comment by michaljaz** [comment]
ok it is working again
