### ISSUE TITLE
Anyway to selfhost and use premium account (microsoft account)

### ISSUE THREAD

**Issue by IThundxr** [michaljaz/webmc#137]
i wanna try playing hypixel skyblock using my own account from a chromebook at school ik it sounds dumb af but is it possible to do that?

**Comment by Mathrandom7910** [comment]
if you have a normal non cracked minecraft account, whats the point of using this when you can use the real launcher?

**Comment by IThundxr** [comment]
being able to join servers through web brower is super useful when you have a device thats locked meaning cant install apps or it doesnt support minecraft
