### ISSUE TITLE
It won't Connect, just keep connecting, anybody have the same prob or just my internet went nuts?

### ISSUE THREAD

**Issue by MilkCafeGo** [michaljaz/webmc#141]

**Comment by michaljaz** [comment]
just mc server is down

**Comment by michaljaz** [comment]
try connect another ip in url param (it should work on 1.16.5 offline mode)

**Comment by unfatefull** [comment]
how do i use offline the server thing is down

**Comment by michaljaz** [comment]
just configure online-mode=false in server.properties
