### ISSUE TITLE
How to use offline mode

### ISSUE THREAD

**Issue by AriGham** [michaljaz/webmc#145]
How do you use offline mode? It just keeps trying to connect to a certain ip but will never load.

**Comment by michaljaz** [comment]
just download 1.16.5 paper mc (https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/790/downloads/paper-1.16.5-790.jar)
easiest way to connect is just tunnel your local server with some tunnelling software like ngrok
and replace server param in minecraft.js.org url

**Comment by michaljaz** [comment]
to enable offline mode just configure online-mode=false in server.properties

**Comment by laparda14** [comment]
Where is server.properties?
