### ISSUE TITLE
The demo never connects

### ISSUE THREAD

**Issue by gwhizoftv** [michaljaz/webmc#146]
On the readme, the demo link is: 
[https://minecraft.js.org/?server=144.24.169.18:25565&nick=SmallPanda&proxy=production](url)

When we go there, it just gives the connecting to... message forever.

If the demo is not working, it should give a message that it is down.
Otherwise we should be able to join the demo.

**Comment by AriGham** [comment]
same here

**Comment by michaljaz** [comment]
You are right. I will add working mc server soon

**Comment by gwhizoftv** [comment]
I tried to connect to our paper server, but it never connects.

**Comment by michaljaz** [comment]
try this temporarly: https://minecraft.js.org/?server=eternalmc.xyz&proxy=production

**Comment by michaljaz** [comment]
![image](https://user-images.githubusercontent.com/26044292/198713757-59ef4443-a75b-45b9-a24b-e459c00c3fc8.png)

**Comment by michaljaz** [comment]
![image](https://user-images.githubusercontent.com/26044292/198713946-45f0a05a-c1cf-4ce1-b63e-7c2f71cb2d54.png)

**Comment by AriGham** [comment]
It works but you can't move at all for some reason

**Comment by AriGham** [comment]
Nvm it works

**Comment by gwhizoftv** [comment]
When I try webmc, I see a flash of connecting to a proxy first. What is the proxy? Do we need to set up one for our client or our servers? Also, which versions of MC are supposed to work with WebMC ?

**Comment by michaljaz** [comment]
proxy is just a bridge between mc server and web browser, so you don't have to setup own proxy becouse, you can just use mine (webmcproxy.glitch.me)
working with 1.16.5 offline mode

**Comment by michaljaz** [comment]
it should work on any 1.16.5 offline mode server

**Comment by gwhizoftv** [comment]
Sorry, what do we need the proxy for? We'd like to run our own.
