### ISSUE TITLE
Stated simpilar plzz?

### ISSUE THREAD

**Issue by AriGham** [michaljaz/webmc#147]
Hello, to connect to a server you said to download ngrok and paper mc but I can't download anything (This is for my school chromebook). Is there any way to access servers without downloading anything? I changed the server IP to play.pvplegacy.net and it connected but kept telling me to log in. I have a real minecraft account, but how do I log in without downloading anything? 

Part 2: 
I wanted to use the offline mode but where is server.properties? Sorry, can you state this as a way a non developer can understand? I tried searching for server.properties in the files but couldn't find anything. Thank you.

**Comment by gwhizoftv** [comment]
+1 for this. Also we need to explain which server releases webmc will work with. The latest MC server is 1.19... Does webMC work with all versions?

**Comment by michaljaz** [comment]
webmc work with 1.16.5
