### ISSUE TITLE
the demo password

### ISSUE THREAD

**Issue by Lqxv** [michaljaz/webmc#152]
when i try to play the demo, it requires a password.

**Comment by yamatyan-kami** [comment]
パスワードとはなんですか

**Comment by yamatyan-kami** [comment]
tell me the password

**Comment by drok28** [comment]
What's the password?

**Comment by A-Random-Person-on-Github** [comment]
change your username in url

**Comment by michaljaz** [comment]
There is a limited list of random nicks in repo, so you just have to change the nick (param in web page url address) to something different and setup own password
