### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Hambone1205** [michaljaz/webmc#167]
When I tried to join your demo server thing It says I need a password. What is the password?

**Comment by BasToTheMax** [comment]
Use a different nick(name)

**Comment by ThisIsNotAGoodUsername1** [comment]
how

**Comment by urahacker** [comment]
yea, where are you supposed to go to change your nick(name)?

**Comment by Breezy20111117** [comment]
how?

**Comment by michaljaz** [comment]
There is a limited list of random nicks in repo, so you just have to change the nick to something different and setup own password
