### ISSUE TITLE
Inventory by div and scss

### ISSUE THREAD

**Issue by fox3000foxy** [michaljaz/webmc#55]
I think its better for put objects correctly in cases

**Comment by fox3000foxy** [comment]
And image of gui is more weight

**Comment by Picoseconds** [comment]
No use Canvas and div only for show item

**Comment by KaffinPX** [comment]
Who is Picoseconds?

**Comment by Picoseconds** [comment]
I am exactly who you think I am

**Comment by KaffinPX** [comment]
Ahaha

**Comment by NexusNull** [comment]
This is github not a kindergarten, please keep your personal dealings in your DMs

**Comment by KaffinPX** [comment]
This guy is a kid.

**Comment by Picoseconds** [comment]
...
