### ISSUE TITLE
I made a webmc installer for ubuntu

### ISSUE THREAD

**Issue by FreddyFeuerstein** [michaljaz/webmc#99]
Hello WebMC community,

I was chatting with some guys on the official discord server who where trying to get this piece of software working. Because the latest node version will not properly install on stock ubuntu and the setup process for webmc is everything but self explanatory, we came to the conclusion that an easy installer for ubuntu desktop and server would be really useful.
So I made it.

# It does the following:

1: Check if the user actually uses ubuntu and if not, exit with error code 130 (fatal error).

2: Add the needed PPA using echo, lsb_release and tee.

3: Update the package list.

4: Install (or if installed upgrade) nodejs and git.

5: Clone the webmc github repo.

6: Install the node modules needed by webmc.

7: Run the postinstall script to prepare webmc.

8: Launch the now fully configured webmc.

# How to install:

1: Download zip file.

2: Extract zip file.

3: Open terminal at the same folder as the .sh file.

4: Run the following as a non-root user that has permission to use sudo:

`chmod +x ./install4linux.sh && ./install4linux.sh`

5: Follow the setup wizard until its done.

# How to run webmc again:

1: Go into the webmc folder.

2: Run the following as a non-root user:

`npm start`

# NOTE:

Run this at your own risk. I tested this on my machine and it worked but that doesn't mean that it will work on any pc without needing modification or preparation. It is very likely that it will work but it might not. If it doesn't, report the error as a comment on this issue.

# 2nd NOTE:

Due to github issues not allowing the upload of .sh files, i needed to zip the script.

**DOWNLOAD LINK:**

[install4linux](https://github.com/michaljaz/webmc/files/6603199/install4linux.sh.zip)

**Comment by SoupSoomer** [comment]
Hello, it seems you have knowledge on how to install this, so can i ask you, how do you install webmc on manjaro?

**Comment by FreddyFeuerstein** [comment]
I mostly use dpkg-based distros but as far as I know, you would have to replace the
apt parts (the update, install and repository add parts) with the following code:
```
sudo pacman -Syu
sudo pacman -S git
sudo pacaur -S nvm
echo 'source /usr/share/nvm/init-nvm.sh' >> ~/.bashrc
exec $SHELL
nvm install 14
echo 'export PATH=$PATH:~/.yarn/bin' >> ~/.bashrc
```
I hope this helped you.

**Comment by pofdzm** [comment]
Would this also work for a ubuntu 18.04 based distro?

**Comment by pofdzm** [comment]
I just tried and it says your system is not running ubuntu lol

**Comment by FreddyFeuerstein** [comment]
> Edit 4: I also realized it didn't asked for my password.

That is because you used sudo before or have the sudo password disabled.

> Edit: I just tried and it says your system is not running ubuntu lol

That is because it checks the release file for the string ubuntu. if you run a ubuntu-based distro like mint for example, it cannot find it and errors out. I guess ill add a --force option for people using such a distro.

> npm ERR! If you do, this is most likely a problem with the webmc package or node itself

It seems that that is actually the problem. You can send the log file in at the nodejs github and ask for a bug fix.

**Comment by FreddyFeuerstein** [comment]
> Edit 4: I also realized it didn't asked for my password.

That is because you used sudo before or have the sudo password disabled.

> Edit: I just tried and it says your system is not running ubuntu lol

That is because it checks the release file for the string ubuntu. if you run a ubuntu-based distro like mint for example, it cannot find it and errors out. I guess ill add a --force option for people using such a distro.

> npm ERR! If you do, this is most likely a problem with the webmc package or node itself

It seems that that is actually the problem. You can send the log file in at the nodejs github and ask for a bug fix.

**Comment by FreddyFeuerstein** [comment]
accidentaly hit the close button

**Comment by SoupSoomer** [comment]
> I mostly use dpkg-based distros but as far as I know, you would have to replace the
> apt parts (the update, install and repository add parts) with the following code:
> 
> ```
> sudo pacman -Syu
> sudo pacman -S git
> sudo pacaur -S nvm
> echo 'source /usr/share/nvm/init-nvm.sh' >> ~/.bashrc
> exec $SHELL
> nvm install 14
> echo 'export PATH=$PATH:~/.yarn/bin' >> ~/.bashrc
> ```
> 
> I hope this helped you.

Thanks, i got it working by looking at the script and manually doing the commands in it replaced with the ones you gave and it seems to be working. im going to test it with my own minecraft server soon. Thank you.

**Comment by FreddyFeuerstein** [comment]
> 
> Thanks, i got it working by looking at the script and manually doing the commands in it replaced with the ones you gave and it seems to be working. im going to test it with my own minecraft server soon. Thank you.

np
